# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

# SPA fallback => toutes les routes reviennent à index.html (offline compris)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
